### ISSUE TITLE
Add rdata fron DNS response to Parquet output

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada2#4]
At present the only drawback we are facing is that ENTRADA2 does not store data from the DNS response message, such as the address that the DNS query resolves to. We would like to ask if this feature is something planned in the future of ENTRADA2 development, as this feature is integral to certain use cases present in our current research, such as the identification of common resolved addresses, leading to the discovery of related domains/IPs.

**Comment by mwullink** [comment]
We could add an optional column to the Parquet output to write rdata from all response RRs? 

The column would need to use a complex type, an example for a response containing an A and AAAA RR could look like this:

[
{ type: 'A', rdata: '1.2.3.4' },
{ type: 'AAAA', rdata: 'dead:beef:ca1f' },
]

**Comment by ukkarikari** [comment]
Looks great! Thank you for your assistance!!

**Comment by mwullink** [comment]
added first version, enable using option: entrada.rdata.enabled = true
 see docs for usage. example sql:

```
select d.data, count(1)
from dns, UNNEST(dns.dns_rdata) d
where d.type = 1 
group by 1 
order by 2 desc  
limit 25;
```
